import {Links, Product, Shop} from "@/assets/types.ts";

export const products:Product[] = [
    {
        "id": "1",
        "name": "Samsung A71 Series Comes with A Screen guard",
        "price": "$70",
        "category": "Smart Phones",
        "description": "A high-end smartphone with a sleek design and powerful features.",
        "discount": "$220",
        "availability": "OUT OF STOCK",
        "brand": "TechBrand",
        "image": "/images/tozo-phone.png",
        "images": [
            "smartphone_x_front.jpg",
            "smartphone_x_back.jpg",
            "smartphone_x_side.jpg"
        ],
        "colors": ["Black", "Silver", "Blue"],
        "deals": "HOT",
        "size": "6.5 inches",
        "capacity": "128GB",
        "cart": true,
        "tag": "New Arrival",
        "quantity": 2,
        "whishlist": true,
        "rating": [5, 4, 4, 5, 5]
    },
    {
        "id": "2",
        "name": "Samsung Galaxy S21 4G. Fast Charging",
        "price": "$2300",
        "category": "Smart Phones",
        "description": "A high-end smartphone with a sleek design and powerful features.",
        "discount": "",
        "availability": "IN STOCK",
        "brand": "TechBrand",
        "image": "/images/blue-phone.png",
        "images": [
            "smartphone_x_front.jpg",
            "smartphone_x_back.jpg",
            "smartphone_x_side.jpg",
            "tv.png",
            "gaming-headphones.png"
        ],
        "colors": [],
        "deals": "",
        "size": "6.5 inches",
        "capacity": "128GB",
        "cart": true,
        "tag": "New Arrival",
        "quantity": 3,
        "whishlist": false,
        "rating": [5, 4, 4, 5, 5]
    },
    {
        "id": "3",
        "name": "Amazon Basics High-Speed HDMI Cable (18Gbps, 4K/6...)",
        "price": "$360",
        "category": "Electronics",
        "description": "A high-end smartphone with a sleek design and powerful features.",
        "discount": "",
        "availability": "In Stock",
        "brand": "TechBrand",
        "image": "/images/high-speed-cable.png",
        "images": [
            "computer-monitor.png",
            "xperia.png",
            "black-beats.png",
            "smartphone_x_side.jpg"
        ],
        "colors": ["Black", "Silver", "Blue"],
        "deals": "BEST DEALS",
        "size": "6.5 inches",
        "capacity": "128GB",
        "cart": false,
        "tag": "New Arrival",
        "quantity": 1,
        "whishlist": true,
        "rating": [5, 4, 4, 5, 5]
    },
    {
        "id": "4",
        "name": "Portable Black Headphones Base Sound",
        "price": "$80",
        "category": "Electronics",
        "description": "A high-end smartphone with a sleek design and powerful features.",
        "discount": "",
        "availability": "IN STOCK",
        "brand": "TechBrand",
        "image": "/images/black-beats.png",
        "images": [
            "gaming-headphones.png",
            "tv.png",
            "xperia.png",
            "computer-monitor.png"
        ],
        "colors": ["Black", "Silver", "Blue"],
        "deals": "",
        "size": "6.5 inches",
        "capacity": "128GB",
        "cart": true,
        "tag": "New Arrival",
        "quantity": 4,
        "whishlist": true,
        "rating": [5, 4, 4, 5, 5]
    },
    {
        "id": "5",
        "name": "Wired Over-Ear Gaming Headphones with USB",
        "price": "$1500",
        "category": "Electronics",
        "description": "A high-end smartphone with a sleek design and powerful features.",
        "discount": "",
        "availability": "In Stock",
        "brand": "TechBrand",
        "image": "/images/gaming-headphones.png",
        "images": [
            "smartphone_x_front.jpg",
            "smartphone_x_back.jpg",
            "smartphone_x_side.jpg",
            "high-speed-cable.png",
            "tozo-phone.png"
        ],
        "colors": ["Black", "Silver", "Blue"],
        "deals": "",
        "size": "6.5 inches",
        "capacity": "128GB",
        "cart": false,
        "tag": "New Arrival",
        "quantity": 50,
        "whishlist": true,
        "rating": [5, 4, 4, 5, 5]
    },
    {
        "id": "6",
        "name": "Polaroid 57-inch Photo/Video Tripod with Delux",
        "price": "$1,200",
        "category": "Electronics",
        "description": "A high-end smartphone with a sleek design and powerful features.",
        "discount": "$1600",
        "availability": "OUT OF STOCK",
        "brand": "TechBrand",
        "image": "/images/tv.png",
        "images": [
            "black-beats.png",
            "blue-phone.png",
            "xperia.png",
            "computer-monitor.png"
        ],
        "colors": ["Black", "Silver", "Blue"],
        "deals": "25% OFF",
        "size": "6.5 inches",
        "capacity": "128GB",
        "cart": false,
        "tag": "Featured Product",
        "quantity": 10,
        "whishlist": true,
        "rating": [5, 4, 4, 5, 5]
    },
    {
        "id": "7",
        "name": "Dell Optiplex 7000x7480 All-in-One Computer Monitor",
        "price": "$250",
        "category": "Electronics",
        "description": "A high-end smartphone with a sleek design and powerful features.",
        "discount": "$1600",
        "availability": "In Stock",
        "brand": "TechBrand",
        "image": "/images/computer-monitor.png",
        "images": [
            "tozo-phone.png",
            "black-beats.png",
            "high-speed-cable.png",
            "gaming-headphones.png"
        ],
        "colors": ["Black", "Silver", "Blue"],
        "deals": "",
        "size": "6.5 inches",
        "capacity": "128GB",
        "cart": true,
        "tag": "New Arrival",
        "quantity": 50,
        "whishlist": false,
        "rating": [5, 4, 4, 5, 5]
    },
    {
        "id": "8",
        "name": "4K UHD LED Smart TV with Chromecast Built-in",
        "price": "$220",
        "category": "Electronics",
        "description": "A high-end smartphone with a sleek design and powerful features.",
        "discount": "$1600",
        "availability": "In Stock",
        "brand": "TechBrand",
        "image": "/images/xperia.png",
        "images": [
            "tv.png",
            "blue-phone.png",
            "computer-monitor.png",
            "black-beats.png"
        ],
        "colors": ["Black", "Silver", "Blue"],
        "deals": "SALE",
        "size": "6.5 inches",
        "capacity": "128GB",
        "cart": true,
        "tag": "New Arrival",
        "quantity": 50,
        "whishlist": false,
        "rating": [5, 4, 4, 5, 5]
    },
    {
        "id": "9",
        "name": "Wireless Bluetooth Earbuds with Charging Case",
        "price": "$150",
        "category": "Accessories",
        "description": "Experience immersive sound with these compact and stylish earbuds.",
        "discount": "$200",
        "availability": "OUT OF STOCK",
        "brand": "SoundTech",
        "image": "/images/tozo-phone.png",
        "images": [
            "smartphone_x_front.jpg",
            "black-beats.png",
            "xperia.png",
            "gaming-headphones.png"
        ],
        "colors": ["White", "Black", "Rose Gold"],
        "deals": "LIMITED OFFER",
        "size": "Universal",
        "capacity": "N/A",
        "cart": false,
        "tag": "Best Seller",
        "quantity": 30,
        "whishlist": true,
        "rating": [4, 5, 5, 4, 5]
    },
    {
        "id": "10",
        "name": "Portable Bluetooth Speaker with 360° Sound",
        "price": "$180",
        "category": "Audio",
        "description": "A powerful speaker that delivers crisp and clear sound in every direction.",
        "discount": "",
        "availability": "In Stock",
        "brand": "SoundWave",
        "image": "/images/black-beats.png",
        "images": [
            "smartphone_x_back.jpg",
            "gaming-headphones.png",
            "xperia.png",
            "tv.png"
        ],
        "colors": ["Black", "Blue", "Red"],
        "deals": "",
        "size": "Compact",
        "capacity": "N/A",
        "cart": false,
        "tag": "Trending",
        "quantity": 45,
        "whishlist": true,
        "rating": [4, 5, 4, 4, 4]
    },
    {
        "id": "11",
        "name": "Smart Fitness Watch with Heart Rate Monitor",
        "price": "$250",
        "category": "Wearables",
        "description": "Keep track of your fitness goals with this advanced smartwatch.",
        "discount": "$300",
        "availability": "In Stock",
        "brand": "FitTech",
        "image": "/images/high-speed-cable.png",
        "images": [
            "computer-monitor.png",
            "gaming-headphones.png",
            "black-beats.png",
            "tv.png"
        ],
        "colors": ["Black", "Silver", "Gold"],
        "deals": "15% OFF",
        "size": "Adjustable",
        "capacity": "64GB",
        "cart": true,
        "tag": "New Arrival",
        "quantity": 20,
        "whishlist": false,
        "rating": [5, 5, 4, 4, 5]
    },
    {
        "id": "12",
        "name": "High-Definition Home Theater Projector",
        "price": "$700",
        "category": "Home Entertainment",
        "description": "Enjoy a cinematic experience at home with this high-definition projector.",
        "discount": "$900",
        "availability": "OUT OF STOCK",
        "brand": "VisionTech",
        "image": "/images/xperia.png",
        "images": [
            "tozo-phone.png",
            "smartphone_x_side.jpg",
            "gaming-headphones.png",
            "high-speed-cable.png"
        ],
        "colors": ["White", "Black"],
        "deals": "20% OFF",
        "size": "Medium",
        "capacity": "N/A",
        "cart": false,
        "tag": "Hot Deal",
        "quantity": 10,
        "whishlist": true,
        "rating": [5, 4, 5, 5, 4]
    },
    {
        "id": "13",
        "name": "Noise-Cancelling Over-Ear Headphones",
        "price": "$300",
        "category": "Audio",
        "description": "Immerse yourself in music with these noise-cancelling headphones.",
        "discount": "",
        "availability": "In Stock",
        "brand": "SoundWave",
        "image": "/images/blue-phone.png",
        "images": [
            "xperia.png",
            "computer-monitor.png",
            "smartphone_x_back.jpg",
            "tv.png"
        ],
        "colors": ["Black", "Gray", "White"],
        "deals": "",
        "size": "Large",
        "capacity": "N/A",
        "cart": true,
        "tag": "Best Seller",
        "quantity": 25,
        "whishlist": false,
        "rating": [4, 5, 5, 4, 4]
    },
    {
        "id": "14",
        "name": "4K Ultra HD Action Camera with Waterproof Case",
        "price": "$200",
        "category": "Cameras",
        "description": "Capture your adventures in stunning 4K resolution with this action camera.",
        "discount": "$250",
        "availability": "In Stock",
        "brand": "AdventureCam",
        "image": "/images/tv.png",
        "images": [
            "gaming-headphones.png",
            "smartphone_x_front.jpg",
            "tozo-phone.png",
            "black-beats.png"
        ],
        "colors": ["Black", "Yellow"],
        "deals": "Limited Offer",
        "size": "Compact",
        "capacity": "32GB",
        "cart": false,
        "tag": "Top Rated",
        "quantity": 15,
        "whishlist": false,
        "rating": [5, 5, 4, 5, 4]
    },
    {
        "id": "15",
        "name": "Wireless Charging Pad for Smartphones",
        "price": "$50",
        "category": "Accessories",
        "description": "Conveniently charge your smartphone without the hassle of cables.",
        "discount": "$60",
        "availability": "In Stock",
        "brand": "ChargeTech",
        "image": "/images/computer-monitor.png",
        "images": [
            "smartphone_x_side.jpg",
            "xperia.png",
            "black-beats.png",
            "tozo-phone.png"
        ],
        "colors": ["Black", "White"],
        "deals": "",
        "size": "Universal",
        "capacity": "N/A",
        "cart": false,
        "tag": "Best Seller",
        "quantity": 100,
        "whishlist": false,
        "rating": [4, 4, 5, 4, 5]
    },
    {
        "id": "16",
        "name": "Ergonomic Wireless Mouse with Adjustable DPI",
        "price": "$40",
        "category": "Accessories",
        "description": "Enhance your productivity with this ergonomic wireless mouse.",
        "discount": "$50",
        "availability": "OUT OF STOCK",
        "brand": "TechBrand",
        "image": "/images/gaming-headphones.png",
        "images": [
            "smartphone_x_front.jpg",
            "tv.png",
            "smartphone_x_back.jpg",
            "high-speed-cable.png"
        ],
        "colors": ["Black", "Red"],
        "deals": "10% OFF",
        "size": "Small",
        "capacity": "N/A",
        "cart": false,
        "tag": "New Arrival",
        "quantity": 75,
        "whishlist": false,
        "rating": [4, 4, 4, 5, 4]
    },
    {
        "id": "17",
        "name": "Smart LED Desk Lamp with USB Charging Port",
        "price": "$45",
        "category": "Home & Office",
        "description": "Brighten your workspace with this smart LED desk lamp featuring a USB charging port.",
        "discount": "$60",
        "availability": "In Stock",
        "brand": "LightTech",
        "image": "/images/tozo-phone.png",
        "images": [
            "xperia.png",
            "black-beats.png",
            "gaming-headphones.png",
            "tv.png"
        ],
        "colors": ["White", "Black"],
        "deals": "SALE",
        "size": "Adjustable",
        "capacity": "N/A",
        "cart": false,
        "tag": "Featured",
        "quantity": 60,
        "whishlist": false,
        "rating": [4, 5, 5, 4, 4]
    },
    {
        "id": "18",
        "name": "High-Speed Portable SSD with 1TB Capacity",
        "price": "$150",
        "category": "Storage",
        "description": "Store and transfer your data quickly with this high-speed portable SSD.",
        "discount": "$180",
        "availability": "In Stock",
        "brand": "DataVault",
        "image": "/images/blue-phone.png",
        "images": [
            "smartphone_x_side.jpg",
            "high-speed-cable.png",
            "tozo-phone.png",
            "gaming-headphones.png"
        ],
        "colors": ["Black", "Gray"],
        "deals": "",
        "size": "Compact",
        "capacity": "1TB",
        "cart": false,
        "tag": "Best Seller",
        "quantity": 40,
        "whishlist": false,
        "rating": [5, 5, 4, 5, 5]
    },
    {
        "id": "19",
        "name": "Smart Air Purifier with HEPA Filter",
        "price": "$220",
        "category": "Home Appliances",
        "description": "Keep your home air clean and fresh with this smart air purifier equipped with a HEPA filter.",
        "discount": "$250",
        "availability": "In Stock",
        "brand": "CleanAir",
        "image": "/images/high-speed-cable.png",
        "images": [
            "tv.png",
            "smartphone_x_back.jpg",
            "xperia.png",
            "black-beats.png"
        ],
        "colors": ["White"],
        "deals": "LIMITED OFFER",
        "size": "Large",
        "capacity": "N/A",
        "cart": false,
        "tag": "Trending",
        "quantity": 30,
        "whishlist": false,
        "rating": [4, 4, 5, 4, 5]
    },
    {
        "id": "20",
        "name": "Wireless Security Camera with Night Vision",
        "price": "$180",
        "category": "Security",
        "description": "Monitor your home with this wireless security camera featuring night vision.",
        "discount": "$200",
        "availability": "In Stock",
        "brand": "SecureHome",
        "image": "/images/black-beats.png",
        "images": [
            "gaming-headphones.png",
            "tv.png",
            "smartphone_x_side.jpg",
            "high-speed-cable.png"
        ],
        "colors": ["Black", "White"],
        "deals": "20% OFF",
        "size": "Compact",
        "capacity": "N/A",
        "cart": false,
        "tag": "New Arrival",
        "quantity": 25,
        "whishlist": false,
        "rating": [5, 5, 4, 4, 4]
    },
    {
        "id": "21",
        "name": "Bluetooth Smart Scale with Body Composition Analysis",
        "price": "$90",
        "category": "Health & Fitness",
        "description": "Track your health with this smart scale that analyzes body composition.",
        "discount": "$100",
        "availability": "In Stock",
        "brand": "HealthTech",
        "image": "/images/gaming-headphones.png",
        "images": [
            "black-beats.png",
            "tv.png",
            "tozo-phone.png",
            "xperia.png"
        ],
        "colors": ["Black", "Silver"],
        "deals": "",
        "size": "Medium",
        "capacity": "N/A",
        "cart": false,
        "tag": "Best Seller",
        "quantity": 50,
        "whishlist": false,
        "rating": [4, 5, 4, 5, 4]
    },
    {
        "id": "22",
        "name": "Portable Solar Charger with Dual USB Ports",
        "price": "$60",
        "category": "Outdoor & Camping",
        "description": "Stay powered up on the go with this portable solar charger.",
        "discount": "$80",
        "availability": "In Stock",
        "brand": "EcoPower",
        "image": "/images/tv.png",
        "images": [
            "smartphone_x_front.jpg",
            "xperia.png",
            "high-speed-cable.png",
            "gaming-headphones.png"
        ],
        "colors": ["Black", "Green"],
        "deals": "SALE",
        "size": "Compact",
        "capacity": "N/A",
        "cart": false,
        "tag": "Top Rated",
        "quantity": 70,
        "whishlist": false,
        "rating": [5, 5, 4, 4, 5]
    },
    {
        "id": "23",
        "name": "Ergonomic Office Chair with Lumbar Support",
        "price": "$300",
        "category": "Furniture",
        "description": "Enhance your productivity and comfort with this ergonomic office chair.",
        "discount": "$350",
        "availability": "In Stock",
        "brand": "ComfortTech",
        "image": "/images/computer-monitor.png",
        "images": [
            "xperia.png",
            "smartphone_x_back.jpg",
            "tv.png",
            "black-beats.png"
        ],
        "colors": ["Black", "Gray"],
        "deals": "15% OFF",
        "size": "Large",
        "capacity": "N/A",
        "cart": false,
        "tag": "Trending",
        "quantity": 20,
        "whishlist": false,
        "rating": [5, 4, 4, 5, 5]
    },
    {
        "id": "24",
        "name": "Smart Coffee Maker with Wi-Fi Control",
        "price": "$120",
        "category": "Kitchen Appliances",
        "description": "Brew your coffee from anywhere with this smart coffee maker featuring Wi-Fi control.",
        "discount": "$140",
        "availability": "In Stock",
        "brand": "BrewMaster",
        "image": "/images/xperia.png",
        "images": [
            "tozo-phone.png",
            "black-beats.png",
            "smartphone_x_front.jpg",
            "tv.png"
        ],
        "colors": ["Black", "Silver"],
        "deals": "",
        "size": "Medium",
        "capacity": "N/A",
        "cart": false,
        "tag": "New Arrival",
        "quantity": 30,
        "whishlist": false,
        "rating": [5, 4, 5, 4, 4]
    },
    {
        "id": "25",
        "name": "Portable Mini Projector with HD Resolution",
        "price": "$130",
        "category": "Electronics",
        "description": "Enjoy movies and presentations on the go with this portable mini projector.",
        "discount": "$150",
        "availability": "In Stock",
        "brand": "ProjectorTech",
        "image": "/images/tozo-phone.png",
        "images": [
            "xperia.png",
            "black-beats.png",
            "gaming-headphones.png",
            "tv.png"
        ],
        "colors": ["Black", "White"],
        "deals": "SALE",
        "size": "Compact",
        "capacity": "N/A",
        "cart": false,
        "tag": "Featured",
        "quantity": 45,
        "whishlist": false,
        "rating": [4, 5, 4, 4, 5]
    },
    {
        "id": "26",
        "name": "Smart Fitness Tracker with Heart Rate Monitor",
        "price": "$85",
        "category": "Health & Fitness",
        "description": "Track your fitness and health metrics with this smart fitness tracker.",
        "discount": "$100",
        "availability": "In Stock",
        "brand": "FitTrack",
        "image": "/images/blue-phone.png",
        "images": [
            "smartphone_x_side.jpg",
            "high-speed-cable.png",
            "tozo-phone.png",
            "gaming-headphones.png"
        ],
        "colors": ["Black", "Blue"],
        "deals": "LIMITED OFFER",
        "size": "Adjustable",
        "capacity": "N/A",
        "cart": false,
        "tag": "Best Seller",
        "quantity": 60,
        "whishlist": false,
        "rating": [5, 4, 5, 5, 4]
    },
    {
        "id": "27",
        "name": "Smart Thermostat with Wi-Fi Connectivity",
        "price": "$220",
        "category": "Home Appliances",
        "description": "Control your home temperature remotely with this smart thermostat.",
        "discount": "$250",
        "availability": "OUT OF STOCK",
        "brand": "HomeComfort",
        "image": "/images/high-speed-cable.png",
        "images": [
            "tv.png",
            "xperia.png",
            "black-beats.png",
            "tozo-phone.png"
        ],
        "colors": ["White", "Gray"],
        "deals": "",
        "size": "Compact",
        "capacity": "N/A",
        "cart": false,
        "tag": "Trending",
        "quantity": 25,
        "whishlist": false,
        "rating": [4, 5, 4, 5, 5]
    },
    {
        "id": "28",
        "name": "Wireless Earbuds with Noise Cancellation",
        "price": "$90",
        "category": "Electronics",
        "description": "Experience high-quality sound with these wireless earbuds featuring noise cancellation.",
        "discount": "$110",
        "availability": "IN STOCK",
        "brand": "SoundWave",
        "image": "/images/black-beats.png",
        "images": [
            "gaming-headphones.png",
            "tv.png",
            "xperia.png",
            "high-speed-cable.png"
        ],
        "colors": ["Black", "White"],
        "deals": "20% OFF",
        "size": "Compact",
        "capacity": "N/A",
        "cart": false,
        "tag": "New Arrival",
        "quantity": 40,
        "whishlist": false,
        "rating": [5, 5, 4, 5, 4]
    },
    {
        "id": "29",
        "name": "Home Robot Vacuum Cleaner with Smart Navigation",
        "price": "$250",
        "category": "Home Appliances",
        "description": "Keep your floors clean with this smart robot vacuum cleaner featuring advanced navigation.",
        "discount": "$280",
        "availability": "OUT OF STOCK",
        "brand": "CleanBot",
        "image": "/images/gaming-headphones.png",
        "images": [
            "black-beats.png",
            "tozo-phone.png",
            "tv.png",
            "xperia.png"
        ],
        "colors": ["White", "Black"],
        "deals": "SALE",
        "size": "Medium",
        "capacity": "N/A",
        "cart": false,
        "tag": "Top Rated",
        "quantity": 20,
        "whishlist": false,
        "rating": [4, 5, 5, 4, 4]
    },
    {
        "id": "30",
        "name": "Electric Kettle with Rapid Boil Function",
        "price": "$35",
        "category": "Kitchen Appliances",
        "description": "Boil water quickly with this electric kettle featuring a rapid boil function.",
        "discount": "$40",
        "availability": "IN STOCK",
        "brand": "KitchenPro",
        "image": "/images/xperia.png",
        "images": [
            "tozo-phone.png",
            "black-beats.png",
            "gaming-headphones.png",
            "tv.png"
        ],
        "colors": ["Silver", "Black"],
        "deals": "",
        "size": "Compact",
        "capacity": "1.7L",
        "cart": false,
        "tag": "New Arrival",
        "quantity": 50,
        "whishlist": false,
        "rating": [5, 4, 5, 4, 5]
    },
    {
        "id": "31",
        "name": "Digital Photo Frame with Wi-Fi Connectivity",
        "price": "$150",
        "category": "Electronics",
        "description": "Display your favorite photos with this digital photo frame featuring Wi-Fi connectivity.",
        "discount": "$180",
        "availability": "IN STOCK",
        "brand": "PhotoFrame",
        "image": "/images/computer-monitor.png",
        "images": [
            "high-speed-cable.png",
            "gaming-headphones.png",
            "xperia.png",
            "tv.png"
        ],
        "colors": ["Black", "Wood"],
        "deals": "15% OFF",
        "size": "Medium",
        "capacity": "N/A",
        "cart": false,
        "tag": "Best Seller",
        "quantity": 35,
        "whishlist": false,
        "rating": [4, 5, 5, 4, 4]
    },
    {
        "id": "31",
        "name": "4K Ultra HD Smart TV with Voice Control",
        "price": "$600",
        "category": "Electronics",
        "description": "Enjoy vivid visuals and smart features with this 4K Ultra HD Smart TV.",
        "discount": "$650",
        "availability": "IN STOCK",
        "brand": "VisionPro",
        "image": "/images/xperia.png",
        "images": [
            "smartphone_x_front.jpg",
            "smartphone_x_back.jpg",
            "smartphone_x_side.jpg",
            "high-speed-cable.png"
        ],
        "colors": ["Black", "Gray"],
        "deals": "HOT DEAL",
        "size": "55 inches",
        "capacity": "N/A",
        "cart": false,
        "tag": "Featured",
        "quantity": 30,
        "whishlist": false,
        "rating": [5, 4, 5, 5, 4]
    },
    {
        "id": "32",
        "name": "Bluetooth Wireless Speaker with Deep Bass",
        "price": "$120",
        "category": "Electronics",
        "description": "Experience high-quality sound with this Bluetooth wireless speaker featuring deep bass.",
        "discount": "$140",
        "availability": "IN STOCK",
        "brand": "SoundMaster",
        "image": "/images/high-speed-cable.png",
        "images": [
            "gaming-headphones.png",
            "black-beats.png",
            "tozo-phone.png",
            "tv.png"
        ],
        "colors": ["Black", "Red"],
        "deals": "20% OFF",
        "size": "Portable",
        "capacity": "N/A",
        "cart": false,
        "tag": "New Arrival",
        "quantity": 40,
        "whishlist": false,
        "rating": [4, 5, 5, 4, 4]
    },
    {
        "id": "33",
        "name": "High-Performance Gaming Laptop with RTX Graphics",
        "price": "$1,500",
        "category": "Electronics",
        "description": "Power your gaming with this high-performance laptop featuring RTX graphics.",
        "discount": "$1,700",
        "availability": "IN STOCK",
        "brand": "GamePro",
        "image": "/images/computer-monitor.png",
        "images": [
            "xperia.png",
            "tozo-phone.png",
            "black-beats.png",
            "gaming-headphones.png"
        ],
        "colors": ["Black", "Silver"],
        "deals": "SALE",
        "size": "17 inches",
        "capacity": "512GB SSD",
        "cart": false,
        "tag": "Top Rated",
        "quantity": 25,
        "whishlist": false,
        "rating": [5, 5, 4, 5, 4]
    },
    {
        "id": "34",
        "name": "Smart Home Security Camera with Night Vision",
        "price": "$200",
        "category": "Electronics",
        "description": "Keep your home safe with this smart security camera featuring night vision.",
        "discount": "$220",
        "availability": "IN STOCK",
        "brand": "SecureHome",
        "image": "/images/gaming-headphones.png",
        "images": [
            "black-beats.png",
            "tv.png",
            "tozo-phone.png",
            "xperia.png"
        ],
        "colors": ["White", "Black"],
        "deals": "",
        "size": "Compact",
        "capacity": "N/A",
        "cart": false,
        "tag": "New Arrival",
        "quantity": 50,
        "whishlist": false,
        "rating": [4, 5, 5, 4, 5]
    },
    {
        "id": "35",
        "name": "Electric Food Processor with Multi-Speed Settings",
        "price": "$150",
        "category": "Kitchen Appliances",
        "description": "Chop, blend, and mix with this versatile food processor featuring multiple speed settings.",
        "discount": "$170",
        "availability": "IN STOCK",
        "brand": "KitchenMaster",
        "image": "/images/computer-monitor.png",
        "images": [
            "tozo-phone.png",
            "black-beats.png",
            "gaming-headphones.png",
            "xperia.png"
        ],
        "colors": ["Silver", "Black"],
        "deals": "15% OFF",
        "size": "Medium",
        "capacity": "2L",
        "cart": false,
        "tag": "Best Seller",
        "quantity": 45,
        "whishlist": false,
        "rating": [5, 4, 4, 5, 5]
    },
    {
        "id": "36",
        "name": "Advanced Smart Watch with GPS and Heart Rate Monitor",
        "price": "$180",
        "category": "Health & Fitness",
        "description": "Track your health and navigate with ease using this advanced smart watch with GPS.",
        "discount": "$200",
        "availability": "IN STOCK",
        "brand": "HealthTrack",
        "image": "/images/xperia.png",
        "images": [
            "high-speed-cable.png",
            "black-beats.png",
            "tozo-phone.png",
            "gaming-headphones.png"
        ],
        "colors": ["Black", "Blue"],
        "deals": "LIMITED OFFER",
        "size": "Adjustable",
        "capacity": "N/A",
        "cart": false,
        "tag": "Featured",
        "quantity": 30,
        "whishlist": false,
        "rating": [5, 5, 4, 5, 4]
    },
];

export const categories = [
    "Computer & Laptop",
    "Smartphone",
    "Headphone",
    "Accessories",
    "Camera & Photo",
    "TV & Homes",
]


export const quickLinks: Links[] = [
    {
        name: "Shop Product",
        link: "/products",
    },
    {
        name: "Shopping Cart",
        link: "#",
    },
    {
        name: "Wishlist",
        link: "#",
    },
    {
        name: "Compare",
        link: "#",
    },
    {
        name: "Track Order",
        link: "#",
    },
    {
        name: "Customer Help",
        link: "/contact",
    },
    {
        name: "About Us",
        link: "/about",
    },
]

export const popularTags: Links[] = [
    {
        name: "Game",
        link: "#",
    },
    {
        name: "iPhone",
        link: "#",
    },
    {
        name: "Laptops",
        link: "#",
    },
    {
        name: "Macbook",
        link: "#",
    },
    {
        name: "Power Bank",
        link: "#",
    },
    {
        name: "SSD",
        link: "#",
    },
    {
        name: "Graphics Card",
        link: "#",
    },
    {
        name: "Smart TV",
        link: "#",
    },
    {
        name: "Speaker",
        link: "#",
    },
    {
        name: "Tablet",
        link: "#",
    },
    {
        name: "Microwave",
        link: "#",
    },
    {
        name: "Samsung",
        link: "#",
    },
]

export const categoriesShop:Shop[] = [
    {
        img: "/images/tv.png",
        title: "Tv & Homes",
    },
    {
        img: "/images/accessories.png",
        title: "Accessories",
    },
    {
        img: "/images/camera-photo.png",
        title: "Camera & Photo",
    },
    {
        img: "/images/desktop.png",
        title: "Desktop",
    },
    {
        img: "/images/head-phones.png",
        title: "Headphones",
    },
    {
        img: "/images/smart-phone.png",
        title: "Smart Phones",
    },
    {
        img: "/images/tv.png",
        title: "Tv & Homes",
    },
    {
        img: "/images/accessories.png",
        title: "Accessories",
    },
    {
        img: "/images/desktop.png",
        title: "Desktop",
    },
    {
        img: "/images/head-phones.png",
        title: "Headphones",
    },
]